logLevel: error
rtsp: yes
rtspAddress: :8554
hls: yes
hlsAddress: :8888
hlsVariant: lowLatency
hlsAlwaysRemux: yes
webrtc: yes
webrtcAddress: :8889
paths:
  ds:
    source: rtsp://127.0.0.1:8555/ds-test
    sourceProtocol: tcp
